Задание 1. Действия над матрицами

In [ ]:
import numpy as np
A = np.matrix([[1, 2, 1],
              [-2, 1, 1]])
B = np.matrix([[3, 1],
               [-1, 0],
               [2, 4]])
C = np.matrix([[-2, 2],
               [1, -1],
               [1, 2]])

# Первое действие выполнить непосредственно нельзя, поэтому транспонируем матрицу B в матрицу BT

BT=np.transpose(B)
print(BT)
l=3
k=4
l+k


[[ 3 -1  2]
 [ 1  0  4]]


7

In [ ]:
A+2*BT

matrix([[7, 0, 5],
        [0, 1, 9]])

In [ ]:
B+2*C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

Задание 2. Матрица с нулями и единицами в шахматном порядке

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Задание 2")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Задание 2
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
